CREATE OR REPLACE TABLE analyst_data.county_classifications (
       FIPSTXT VARCHAR NULL,
       STATE VARCHAR NULL,
       COUNTY VARCHAR NULL,
       RURALURBANCONTINUUMCODE2013 FLOAT NULL,
       URBANINFLUENCECODE2013 FLOAT NULL,
       RURALURBANCONTINUUMCODE2003 FLOAT NULL,
       URBANINFLUENCECODE2003 FLOAT NULL,
       METRO2013 FLOAT NULL,
       NONMETRO2013 FLOAT NULL,
       MICROPOLITAN2013 FLOAT NULL,
       TYPE_2015_UPDATE FLOAT NULL,
       TYPE_2015_FARMING_NO FLOAT NULL,
       TYPE_2015_MANUFACTURING_NO FLOAT NULL,
       TYPE_2015_MINING_NO FLOAT NULL,
       TYPE_2015_GOVERNMENT_NO FLOAT NULL,
       TYPE_2015_RECREATION_NO FLOAT NULL,
       LOW_EDUCATION_2015_UPDATE FLOAT NULL,
       LOW_EMPLOYMENT_2015_UPDATE FLOAT NULL,
       POPULATION_LOSS_2015_UPDATE FLOAT NULL,
       RETIREMENT_DESTINATION_2015_UPDATE FLOAT NULL,
       PERPOV_1980_0711 FLOAT NULL,
       PERSISTENTCHILDPOVERTY_1980_2011 FLOAT NULL,
       HIPOV FLOAT NULL,
       HIAMENITY FLOAT NULL,
       HICREATIVECLASS2000 FLOAT NULL,
       GAS_CHANGE FLOAT NULL,
       OIL_CHANGE FLOAT NULL,
       OIL_GAS_CHANGE FLOAT NULL,
       METRO2003 FLOAT NULL,
       NONMETRONOTADJ2003 FLOAT NULL,
       NONMETROADJ2003 FLOAT NULL,
       NONCORE2003 FLOAT NULL,
       ECONOMICDEPENDENCE2000 FLOAT NULL,
       NONMETRO2003 FLOAT NULL,
       MICROPOLITAN2003 FLOAT NULL,
       FARMDEPENDENT2003 FLOAT NULL,
       MANUFACTURINGDEPENDENT2000 FLOAT NULL,
       LOWEDUCATION2000 FLOAT NULL,
       RETIREMENTDESTINATION2000 FLOAT NULL,
       PERSISTENTPOVERTY2000 FLOAT NULL,
       NONCORE2013 FLOAT NULL,
       TYPE_2015_NONSPECIALIZED_NO FLOAT NULL,
       METRO_ADJACENT2013 FLOAT NULL,
       PERSISTENTCHILDPOVERTY2004 FLOAT NULL,
       RECREATIONDEPENDENT2000 FLOAT NULL
       );


put 'file://c:/users/matth/downloads/county classifications.csv' @bookbub.analyst_data.%county_classifications 
parallel = 99
auto_compress = TRUE
overwrite = TRUE
;

/*
* load the data into the newly created empty table
*/
-- TRUNCATE TABLE analyst_data.county_classifications;
COPY INTO bookbub.analyst_data.county_classifications
FROM @bookbub.analyst_data.%county_classifications
file_format = (
type = 'CSV'
compression = 'gzip'
field_delimiter = '\t'
skip_header = 1
--error_on_column_count_mismatch=FALSE
--encoding='UTF8'
escape = '\\'
trim_space = TRUE
null_if = ('NULL','null','\\N', '')
-- error_on_column_count_mismatch = TRUE
empty_field_as_null = TRUE
-- replace_invalid_characters = TRUE
validate_utf8 = TRUE
encoding = 'UTF8'
)